name: slickformer
channels:
    - conda-forge
    - pytorch
    - nvidia
dependencies:
    - albumentations
    - black
    - boto3
    - dask
    - distributed
    - fastapi
    - gcc
    - geojson
    - geopandas
    - geoalchemy2
    - graphviz
    - httpx
    - hydra-core
    - ipykernel
    - jpeg
    - libpng
    - matplotlib
    - opencv
    - pandas
    - pip
    - python-graphviz
    - pytorch-cuda==11.7
    - pysal
    - pystac-client
    - rasterio
    - rioxarray
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - supermercado
    - tensorboard
    - timm
    - torchmetrics
    - transformers
    - xbatcher
    - zen3geo
    - pip:
        - git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0
        - git+https://github.com/waspinator/pycococreator.git@0.2.1
        - rio-cogeo
        - rio-tiler-pds
        - torch==2.0
        - pytorch-lightning==2.0
        - torchdata==0.6
        - torchvision
        - global-land-mask