name: slickformer
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pip=22.0.4
    - cudatoolkit
    - transformers
    - pytorch-lightning
    - black
    - pip:
      - git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0