name: slickformer
channels:
    - conda-forge
    - nodefaults
dependencies:
    - albumentations
    - black
    - boto3
    - cython>=0.27.3
    - dask
    - distributed
    - fastapi
    - gcc
    - geojson
    - geopandas
    - geoalchemy2
    - graphviz
    - httpx
    - hydra-core
    - ipykernel
    - jpeg
    - libpng
    - matplotlib
    - opencv
    - pandas
    - pip
    - pycocotools
    - python-graphviz
    - pysal
    - pystac-client
    - rasterio
    - rioxarray
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - supermercado
    - tensorboard
    - timm
    - torchmetrics
    - transformers
    - xbatcher
    - zen3geo
    - lightning>=2.0
    - pytorch>=2.0
    - torchdata>=0.6
    - torchvision
    - pip:
        - rio-cogeo
        - rio-tiler-pds
        - global-land-mask