name: slickformer
channels:
    - conda-forge
dependencies:
    - python=3.8
    - pip=22.0.4
    - cudatoolkit-dev=11.3
    - opencv=4.4.0
    - iopath<0.1.10,>=0.1.7
    - hydra-core>=1.1
    - omegaconf>=2.1
    - wandb=0.13.10
    - black
    - pip:
      - git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0
      - torch==1.10.1
      - torchvision==0.11.2
      - https://dl.fbaipublicfiles.com/detectron2/wheels/cu113/torch1.10/detectron2-0.6%2Bcu113-cp38-cp38-linux_x86_64.whl
